'use client'

import React from 'react'
import Header from '@/components/navbar'
import MultimodalInput from '@/components/multimodal-input'
import { useChat } from 'ai/react'

export default function Layout({ children }: { children: React.ReactNode }) {
  const {
    input,
    setMessages,
    isLoading,
    stop,
    handleInputChange,
    handleSubmit,
  } = useChat()

  return (
    <>
      <Header setMessages={setMessages} />
      {children}
      <div className="mt-auto px-2 w-full">
        <MultimodalInput
          input={input}
          isLoading={isLoading}
          stop={stop}
          handleInputChange={handleInputChange}
          handleSubmit={handleSubmit}
        />
      </div>
      <span className="text-xs text-zinc-500 py-2 mx-auto text-center">
        Message are generated by AI and may be inaccurate or inappropriate.
      </span>
    </>
  )
}
