'use client'

import React from 'react'
import SidebarContent from '@/components/sidebar-content'
import Header from '@/components/navbar'
import MultimodalInput from '@/components/multimodal-input'
import { useChat } from 'ai/react'
import { useSelector } from 'react-redux'
import { RootState } from '@/store/store'

export default function Layout({ children }: { children: React.ReactNode }) {
  const {
    input,

    setMessages,
    isLoading,
    stop,
    handleInputChange,
    handleSubmit,
  } = useChat()
  const isSidebar = useSelector((state: RootState) => state.chat.isSidebarOpen)

  return (
    <main className="h-svh flex ">
      <div
        className={`${
          isSidebar ? 'w-64 visible' : ' w-0 invisible'
        } z-[1] flex-shrink-0 overflow-x-hidden transition-all duration-300 border-r border-gray-200 absolute sm:relative h-full bg-white`}
      >
        <SidebarContent setMessages={setMessages} />
      </div>
      <div className="w-full flex flex-col items-center px-2 ">
        <Header setMessages={setMessages} />
        {children}
        <div className="mt-auto px-2 w-full">
          <MultimodalInput
            input={input}
            isLoading={isLoading}
            stop={stop}
            handleInputChange={handleInputChange}
            handleSubmit={handleSubmit}
          />
        </div>
        <span className="text-xs text-zinc-500 py-2 mx-auto text-center">
          Message are generated by AI and may be inaccurate or inappropriate.
        </span>
      </div>
    </main>
  )
}
