"use client"

import Logo from "@/components/Logo"
import Header from "@/components/Header"
import {
  FileText,
  Edit3,
  Briefcase,
  Book,
  Map,
  Gift,
  Coffee,
} from "react-feather"
import TextInputField from "@/components/TextInputField"
import SendMessage from "@/components/SendMessage"
import ReceivedMessage from "@/components/ReceivedMessage"
import { useChat } from "ai/react"

export default function HomePage() {
  //const messageList = useSelector((state) => state.conversation.messageList);
  const { messages, input, handleInputChange, handleSubmit, setMessages } =
    useChat()

  return (
    <>
      {messages.length === 0 ? (
        <Main
          input={input}
          handleInputChange={handleInputChange}
          setMessages={setMessages}
          handleSubmit={handleSubmit}
        />
      ) : (
        <MessageContent
          messages={messages}
          setMessages={setMessages}
          input={input}
          handleInputChange={handleInputChange}
          handleSubmit={handleSubmit}
        />
      )}
    </>
  )
}

function Main({ input, handleInputChange, handleSubmit }) {
  return (
    <>
      <main className="min-h-svh flex flex-col items-center justify-center px-2">
        <Header />

        <div className="flex flex-col w-full flex-1 items-center justify-center gap-5 ">
          <div className="hover:scale-110 transition-transform duration-200">
            <Logo size={60} />
          </div>
          <h2 className="text-2xl font-semibold">Hi, how can I help you?</h2>
          <TextInputField
            input={input}
            handleInputChange={handleInputChange}
            handleSubmit={handleSubmit}
          />
          <div className="flex flex-wrap justify-center gap-2 max-w-[48rem]">
            <ItemSugesstion title="Summarize text">
              <FileText size={24} color="#e2c542" />
            </ItemSugesstion>
            <ItemSugesstion title="Get advice">
              <Book size={24} color="#ea8445" />
            </ItemSugesstion>
            <ItemSugesstion title="Make a plan">
              <Briefcase size={24} color="#6c71ff" />
            </ItemSugesstion>
            <ItemSugesstion title="Help me write">
              <Edit3 size={24} color="#76d0eb" />
            </ItemSugesstion>
            <ItemSugesstion title="Tell me a joke">
              <Coffee size={24} color="#cb8bd0" />
            </ItemSugesstion>
            <ItemSugesstion title="What's fun there">
              <Map size={24} color="#76d0eb" />
            </ItemSugesstion>
            <ItemSugesstion title="Suprise me">
              <Gift size={24} color="#ea8445" />
            </ItemSugesstion>
          </div>
        </div>

        <span className="text-xs text-zinc-500 py-2 mx-auto text-center">
          Message are generated by AI and may be inaccurate or inappropriate.
        </span>
      </main>
    </>
  )
}

function ItemSugesstion({ children, title }) {
  return (
    <button
      className="flex rounded-full py-2 px-4 gap-2 hover:shadow-sm transition-colors duration-300
     hover:bg-zinc-50 items-center border border-gray-200 text-gray-600 text-sm
     w-[calc(50%-0.5rem)] sm:w-auto"
    >
      {children}
      <span>{title}</span>
    </button>
  )
}

function MessageContent({
  messages,
  setMessages,
  input,
  handleInputChange,
  handleSubmit,
}) {
  return (
    <main className="h-svh flex flex-col px-2">
      <Header setMessages={setMessages} />

      <div className="flex-grow overflow-auto px-2">
        <div className="mx-auto max-w-3xl w-full">
          <Message messages={messages} />
        </div>
      </div>

      <div className="mt-auto px-2">
        <TextInputField
          input={input}
          handleInputChange={handleInputChange}
          handleSubmit={handleSubmit}
        />
      </div>
      <span className="text-xs text-zinc-500 py-2 mx-auto text-center">
        Message are generated by AI and may be inaccurate or inappropriate.
      </span>
    </main>
  )
}

function Message({ messages }) {
  return (
    <>
      {messages.map((message, index) => (
        <article key={index} className="my-5 w-full">
          {message.role === "user" ? (
            <SendMessage message={message.content} />
          ) : (
            <ReceivedMessage message={message.content} />
          )}
        </article>
      ))}
    </>
  )
}
