"use client"

import { useState, useRef, useEffect } from "react"
import { ArrowUp } from "react-feather"
import { useDispatch } from "react-redux"
import { addMessage } from "@/store/conversationSlice"
export default function TextInputField() {
  const [isDisabled, setIsDisabled] = useState(true)
  const [inputMessage, setInputMessage] = useState("")

  const dispatch = useDispatch()

  const textareaRef = useRef(null)

  useEffect(() => {
    adjustTextareaHeight()
  }, [inputMessage])

  const adjustTextareaHeight = () => {
    const textarea = textareaRef.current
    if (textarea) {
      textarea.style.height = "auto"
      textarea.style.height = `${textarea.scrollHeight}px`
    }
  }

  const handleSubmit = async () => {
    dispatch(addMessage({ content: inputMessage, role: "user" }))
    setInputMessage("")

    const response = await fetch("/api/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        message: { content: inputMessage, role: "user" },
      }),
    })
    const data = await response.json()
    dispatch(
      addMessage({
        content: data.choices[0]?.message?.content,
        role: data.choices[0]?.message?.role,
      })
    )
    setIsDisabled(true)
  }
  return (
    <div className="mx-auto w-full items-center flex flex-col">
      <div
        className="flex items-center justify-between max-w-[48rem] w-full border border-gray-200 p-2 rounded-[2rem] h-full
      transition-colors duration-300 hover:bg-neutral-50 hover:shadow-sm overflow-hidden"
      >
        <div className="flex items-center pl-4 w-full h-full overflow-hidden">
          <textarea
            ref={textareaRef}
            placeholder="Enter text here"
            className="w-full focus:outline-none bg-transparent resize-none overflow-y-auto max-h-[25dvh]"
            value={inputMessage}
            onChange={(e) => {
              setInputMessage(e.target.value)
              setIsDisabled(e.target.value.trim() === "")
            }}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault()
                handleSubmit()
              }
            }}
            rows={1}
          />
        </div>
        <button
          className={`ml-2  text-white p-2 rounded-full self-end ${
            isDisabled ? "bg-zinc-200" : "bg-black"
          }`}
          onClick={handleSubmit}
          disabled={isDisabled}
        >
          <ArrowUp size={24} />
        </button>
      </div>
      <span className="text-xs text-zinc-500 py-1 mx-auto">
        Message are generated by AI and may be inaccurate or inappropriate.
      </span>
    </div>
  )
}
